### ISSUE TITLE
http://rdfshape.weso.es is down

### ISSUE THREAD

**Issue by VladimirAlexiev** [validatingrdf/validatingrdf.github.io#18]
@labra Help! Your excellent service is down.

Not sure this is the right project to post this to, let me know if there's a better one
- you refer to this service in #15
- I want to try the links in your excellent presentation https://docs.google.com/presentation/d/e/2PACX-1vRfDdQK6FU8GqTTRZZTi8R1RqCix53yBalaWWIiXIddk1R1Wk3clRCX24ewRanTY9-Jfv17zX-V0D4F/pub?start=false&loop=false&delayms=3000&slide=id.g420c7cedd6_2_137
- and in this one https://docs.google.com/presentation/d/e/2PACX-1vSsAVC0VLHJjg_xoOuxHORFzSBNuiCTye8-X_jfR9DxfHGkgwJnz4vVrmX3BI7x8ZuYWivKmqvv5PRE/pub?start=false&loop=false&delayms=3000&slide=id.g49668af87f_2_70

cc @bmzernichow

**Comment by labra** [comment]
Thanks, I tried it and it seems to be up again.

The rdfshape.weso.es is deployed in one of my University servers which allowed me to deploy it there for free.

The rdfshape.herokuapp.com is deployed at heroku for free also, after 20 days or so, it consumes all free dyno hours and is shut down. 

I would be happy to deploy it in a better place.

**Comment by VladimirAlexiev** [comment]
Weird. I tried the link from #15 and Chrome again says "This site can’t be reached rdfshape.weso.es took too long to respond."
Looked in c-s-J Network tab but there isn't much to see, it just says the request has stalled.

```
>telnet rdfshape.weso.es 80
Trying 156.35.94.30...
telnet: Unable to connect to remote host: Connection timed out
```
Also
```
>tracert rdfshape.weso.es

Tracing route to rdfshape.weso.es [156.35.94.30]
over a maximum of 30 hops:

  1     4 ms     1 ms     1 ms  192.168.1.1
  2     4 ms     4 ms     3 ms  82.118.248.1
  3     4 ms     2 ms     4 ms  core.vipnetbg.com [78.130.178.129]
  4     3 ms     4 ms     3 ms  JMX01.sof1.net.telehouse.bg [178.132.82.1]
  5     5 ms     3 ms     3 ms  ae1-124.RT.TLP.SOF.BG.retn.net [87.245.240.145]
  6    61 ms    57 ms    57 ms  ae2-4.RT.IRX.MAD.ES.retn.net [87.245.233.191]
  7    73 ms    89 ms    72 ms  rediris.baja.espanix.net [193.149.1.26]
  8    77 ms    76 ms    75 ms  ciemat.ae2.uva.rt1.cyl.red.rediris.es [130.206.245.10]
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
 11     *        *        *     Request timed out.
 12     *        *        *     Request timed out.
```

**Comment by VladimirAlexiev** [comment]
> I would be happy to deploy it in a better place.

What do you need (as in, what cloud is Heroku?)
I'll ask at Onto (my ref: https://ontotext.slack.com/archives/C72BNG02C/p1544176236001600)

**Comment by labra** [comment]
You mean [this link](http://rdfshape.weso.es/validate?data=%40prefix%20%3A%20%20%20%20%20%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20.%0A%40prefix%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%20.%0A%40prefix%20sh%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20.%0A%40prefix%20xsd%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20.%0A%40prefix%20foaf%3A%20%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%20.%0A%0A%3Aalice%20%20a%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3AUser%20%3B%0A%20%20%20%20%20%20%20%20schema%3AworksFor%20%20%3AaCompany%20.%0A%0A%3Abob%20%20%20%20a%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3AUser%20%3B%0A%20%20%20%20%20%20%20%20schema%3AworksFor%20%20%3AwrongCompany%20.%0A%0A%3AaCompany%20%20schema%3Aname%20%20%22ACompany%22%20.%0A%3AwrongCompany%20%20schema%3Aname%20%2023%20.%0A&dataFormat=TURTLE&schema=prefix%20%3A%20%20%20%20%20%20%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20%0Aprefix%20sh%3A%20%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20%0Aprefix%20xsd%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0Aprefix%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0Aprefix%20foaf%3A%20%20%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0Aprefix%20rdfs%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20%20%20%20%20%20%20%0A%3AUserShape%20a%20sh%3ANodeShape%3B%0A%20%20sh%3AtargetClass%20%3AUser%20%3B%0A%20%20sh%3Aproperty%20%5B%0A%20%20%20sh%3Apath%20schema%3AworksFor%20%3B%0A%20%20%20sh%3Anode%20%3ACompanyShape%20%3B%0A%20%20%5D%20.%0A%0A%3ACompanyShape%20a%20sh%3ANodeShape%20%3B%0A%20%20sh%3Aproperty%20%5B%0A%20%20%20sh%3Apath%20schema%3Aname%20%3B%0A%20%20%20sh%3Adatatype%20xsd%3Astring%20%3B%0A%20%20%5D%20.%0A&schemaFormat=Turtle&schemaEngine=SHACLex&triggerMode=TargetDecls&schemaEmbedded=false&inference=NONE&activeDataTab=%23dataTextArea&activeSchemaTab=%23schemaTextArea&activeShapeMapTab=%23shapeMapTextArea&&shapeMap=)? 

Because it works from my laptop...this is the output I get from `ping`: 

```
> ping rdfshape.weso.es
PING rdfshape.weso.es (156.35.94.30) 56(84) bytes of data.
64 bytes from 156.35.94.30: icmp_seq=1 ttl=51 time=13.3 ms
64 bytes from 156.35.94.30: icmp_seq=2 ttl=51 time=16.0 ms
64 bytes from 156.35.94.30: icmp_seq=3 ttl=51 time=12.7 ms
64 bytes from 156.35.94.30: icmp_seq=4 ttl=51 time=14.3 ms
^C
```

It is really weird...are you behind some proxy or firewall?

**Comment by VladimirAlexiev** [comment]
That link. No particular proxy, the first trace steps are just my internet provider. 
```
>ping rdfshape.weso.es

Pinging rdfshape.weso.es [156.35.94.30] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
```

**Comment by labra** [comment]
I'm afraid I forgot about this issue, @VladimirAlexiev, if you are able to connect to http://rdfshape.weso.es I think I can close the issue.

**Comment by labra** [comment]
Closed as I think rdfshape is accessible now.
